algoritmo "Enquanto++"
var
numero,soma,limite:real
inicio
escreval("Bem-vindo ao sistema de cálculos.")
escreval("")
escreval("Insira o número limite de sua contagem: ")
leia(limite)
escreval("")
escreval("insira o intervalo em que deseja que os valores sejam somados: ")
leia(soma)
escreval("")
enquanto (numero<=limite) faca
escreval(numero)
numero<-numero+soma
fimenquanto
escreval("Término da sequência.")
fimalgoritmo
