SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE,
	SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE DATABASE veiculo;
USE veiculo;

CREATE TABLE IF NOT EXISTS `veiculo`.`categoria` (
	`idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
	`categoria` VARCHAR(45) NULL DEFAULT NULL,
	
	PRIMARY KEY (`idCategoria`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `veiculo`.`marca` (
	`idMarca` INT(11) NOT NULL AUTO_INCREMENT,
	`marca` VARCHAR(45) NULL DEFAULT NULL,
	
	PRIMARY KEY (`idMarca`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `veiculo`.`modelo` (
	`idModelo` INT(11) NOT NULL AUTO_INCREMENT,
	`modelo` VARCHAR(45) NULL DEFAULT NULL,
	`marca_idMarca` INT(11) NOT NULL,

	PRIMARY KEY (`idModelo`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `veiculo`.`proprietario` (
	`idProprietario` INT(11) NOT NULL AUTO_INCREMENT,
	`cpf` VARCHAR(45) NULL DEFAULT NULL,
	`nome` VARCHAR(45) NULL DEFAULT NULL,

	PRIMARY KEY (`idProprietario`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `veiculo`.`veiculo` (
	`idVeiculo` INT(11) NOT NULL AUTO_INCREMENT,
	`renavam` VARCHAR(20) NULL DEFAULT NULL,
	`placa` VARCHAR(7) NULL DEFAULT NULL,
	`idCategoria` INT(11) NOT NULL,
	`idModelo` INT(11) NOT NULL,
	`idProprietario` INT(11) NOT NULL,

	PRIMARY KEY (`idVeiculo`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
